#!/bin/sh /etc/rc.common
# /etc/init.d/vcrt_bot
START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/vcrt_bot.sh

start_service() {
    [ -x "$PROG" ] || chmod +x "$PROG" 2>/dev/null
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall -9 vcrt_bot.sh 2>/dev/null || true
}

reload_service() {
    stop
    start
}
