#!/bin/sh
# VCRT OS v2.0 - Shared Constants (CGI + Telegram Daemon)
export BLOCKS_TIMED_FILE="/tmp/vcrt_blocks_timed.db"
export BLOCKED_SOFT_FILE="/tmp/vcrt_blocked_soft.db"
export BLOCKED_HARD_FILE="/tmp/vcrt_blocked_hard.db"
export SESSIONS_DIR="/tmp/vcrt_sessions"
export CONFIG_DIR="/etc/vcrt"
export AUTH_FILE="/etc/vcrt/passwd"
export SALT_FILE="/etc/vcrt/salt"
export TRAFFIC_DAILY_DB="/etc/vcrt/traffic_daily.db"
export TRAFFIC_HOURLY_DB="/etc/vcrt/traffic_hourly.db"
export DEVICE_NAMES_FILE="/etc/vcrt/device_names"
export VERSION_FILE="/etc/vcrt/version"
export TELEGRAM_CONF="/etc/vcrt/telegram.conf"
export NEXTDNS_APIKEY="/etc/vcrt_nextdns_apikey"
export NEXTDNS_CONF_FILE="/etc/vcrt_nextdns_profile"
export NEXTDNS_TOKEN_FILE="/etc/vcrt_nextdns_token"
export PEAK_BW_FILE="/tmp/vcrt_peak_bw.tmp"
export PREV_WAN_BYTES="/tmp/vcrt_prev_wan_bytes.tmp"
export WIRELESS_BACKUP="/tmp/vcrt_wireless.bak"
export CPU_TMP_FILE="/tmp/vcrt_cpu.tmp"
export BW_TMP_FILE="/tmp/vcrt_bw.tmp"
export DF_TMP_FILE="/tmp/vcrt_df.tmp"
export MODEL_TMP_FILE="/tmp/vcrt_model.tmp"
export OSINFO_TMP_FILE="/tmp/vcrt_osinfo.tmp"
export ISP_TMP_FILE="/tmp/vcrt_isp.tmp"
export NEXTDNS_LINKED_IP_TMP="/tmp/vcrt_nextdns_linked_ip.tmp"
